# Generated by Django 4.2.20 on 2025-04-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_price_product_installation_cost_and_more'),
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='city',
            field=models.CharField(default='Birmingham', max_length=16),
        ),
        migrations.AddField(
            model_name='installation',
            name='county',
            field=models.CharField(default='West Midlands', max_length=32),
        ),
        migrations.AddField(
            model_name='installation',
            name='first_line',
            field=models.CharField(default='1a Moor Street', max_length=64),
        ),
        migrations.AddField(
            model_name='installation',
            name='postcode',
            field=models.CharField(default='B5 4BU', max_length=8),
        ),
        migrations.AddField(
            model_name='installation',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
