# Generated by Django 4.2.20 on 2025-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_installation_city_installation_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='city',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='installation',
            name='county',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='installation',
            name='first_line',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='installation',
            name='postcode',
            field=models.CharField(default='', max_length=8),
        ),
    ]
