# Generated by Django 5.1.2 on 2024-10-15 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('time', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='is_alive',
            field=models.BooleanField(default=False),
        ),
    ]
