# Generated by Django 5.1.2 on 2024-10-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_booking_artist_is_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='teacher',
            field=models.CharField(default=None, max_length=225),
        ),
    ]
