# Generated by Django 5.1.2 on 2024-10-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_booking_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='teacher',
            field=models.CharField(choices=[('JW', 'James Williams'), ('HG', 'Hana Goodwill'), ('SJ', 'Sarah Jones'), ('CS', 'Chad Smith'), ('LS', 'Luis Suarez'), ('LJ', 'LeBron James')], max_length=225),
        ),
    ]
