# Generated by Django 5.1.4 on 2024-12-06 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'permissions': (('can_create_own_course', 'Create a new course'), ('can_edit_own_course', 'Edit one of your existing courses'), ('can_delete_own_course', 'Delete one of your existing courses'), ('can_create_lesson', 'Create a new lessons'), ('can_edit_own_lesson', 'Edit one of your existing lessons'), ('can_delete_own_lesson', 'Delete one of your existing lessons'), ('add_course_to_account', 'Add course to your account'), ('remove_course_from_account', 'Remove course from account'))},
        ),
        migrations.RemoveField(
            model_name='learner',
            name='groups',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tutor'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
