# Generated by Django 5.1.4 on 2024-12-06 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tutor_options_remove_learner_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 8, 1, 51, 759829)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 8, 1, 51, 760110)),
        ),
    ]
