# Generated by Django 5.1.4 on 2024-12-06 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_date_posted_alter_lesson_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 8, 6, 59, 429968)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 8, 6, 59, 430223)),
        ),
    ]
