# Generated by Django 5.1.4 on 2024-12-06 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_course_date_posted_alter_lesson_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'permissions': (('can_view_own_models', 'View own models'), ('can_create_own_course', 'Create a new course'), ('can_edit_own_course', 'Edit one of your existing courses'), ('can_delete_own_course', 'Delete one of your existing courses'), ('can_create_lesson', 'Create a new lessons'), ('can_edit_own_lesson', 'Edit one of your existing lessons'), ('can_delete_own_lesson', 'Delete one of your existing lessons'), ('add_course_to_account', 'Add course to your account'), ('remove_course_from_account', 'Remove course from account'))},
        ),
        migrations.AlterField(
            model_name='course',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 12, 11, 17, 997270)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 12, 11, 17, 997677)),
        ),
    ]
