# Generated by Django 5.1.4 on 2024-12-06 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_tutor_options_alter_course_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learner',
            options={'permissions': (('add_course_to_account', 'Add course to your account'), ('remove_course_from_account', 'Remove course from account'), ('can_view_learner_dashboard', 'Go to dashboard'))},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'permissions': (('can_view_own_models', 'View own models'), ('can_view_tutor_dashboard', 'Go to dashboard'), ('can_create_own_course', 'Create a new course'), ('can_edit_own_course', 'Edit one of your existing courses'), ('can_delete_own_course', 'Delete one of your existing courses'), ('can_create_lesson', 'Create a new lessons'), ('can_edit_own_lesson', 'Edit one of your existing lessons'), ('can_delete_own_lesson', 'Delete one of your existing lessons'), ('add_course_to_account', 'Add course to your account'), ('remove_course_from_account', 'Remove course from account'))},
        ),
        migrations.AlterField(
            model_name='course',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 12, 18, 18, 139959)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 12, 18, 18, 140222)),
        ),
    ]
