# Generated by Django 5.1.4 on 2024-12-06 12:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_course_date_posted_alter_lesson_date_posted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 12, 37, 33, 243031)),
        ),
        migrations.AlterField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 12, 37, 33, 243322)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
