# Generated by Django 5.1.4 on 2024-12-11 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_course_learners_alter_course_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'permissions': (('can_view_own_models', 'View own models'), ('can_view_tutor_dashboard', 'Go to dashboard'), ('can_create_own_course', 'Create a new course'), ('can_edit_own_course', 'Edit one of your existing courses'), ('can_delete_own_course', 'Delete one of your existing courses'), ('can_create_lesson', 'Create a new lessons'), ('can_edit_own_lesson', 'Edit one of your existing lessons'), ('can_delete_own_lesson', 'Delete one of your existing lessons'))},
        ),
        migrations.AlterField(
            model_name='course',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 9, 27, 33, 278205)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 9, 27, 33, 278726)),
        ),
    ]
