# Generated by Django 5.1.4 on 2024-12-12 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_tutor_options_alter_course_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 12, 8, 46, 0, 482473)),
        ),
        migrations.AlterField(
            model_name='course',
            name='learners',
            field=models.ManyToManyField(blank=True, related_name='courses', to='main.learner'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 12, 8, 46, 0, 483456)),
        ),
    ]
