# Generated by Django 5.1.4 on 2024-12-12 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_course_author_alter_course_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 12, 9, 29, 45, 194360)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 12, 9, 29, 45, 194906)),
        ),
    ]
