# Generated by Django 5.1.4 on 2024-12-13 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_course_date_posted_alter_lesson_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 13, 7, 41, 31, 198953)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 13, 7, 41, 31, 199560)),
        ),
    ]
