# Generated by Django 4.2.20 on 2025-04-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='date_time',
        ),
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
