# Generated by Django 4.2.20 on 2025-04-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_consultation_date_time_consultation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
