# Generated by Django 5.1.5 on 2025-02-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('datetime', models.CharField(max_length=225)),
                ('children', models.IntegerField()),
                ('adults', models.IntegerField()),
            ],
        ),
    ]
