# Generated by Django 5.1.3 on 2024-11-22 20:57

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cakes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recipes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200, null=True),
        ),
    ]
