# Generated by Django 4.2.20 on 2025-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
