# Generated by Django 4.2.20 on 2025-03-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
